name: reusable-react-deploy

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
      deploy-path:
        required: false
        type: string
        default: './deploy'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.deploy-path }}

      - name: Verify artifact contents
        run: |
          echo "Contents of deployment folder:"
          ls -la ${{ inputs.deploy-path }}
